### PR TITLE
jnr-a64asm : remote assembler to support aarch64

### PR DESCRIPTION
**Pull request by ossdev07**
added support of AARCH64 in jnr-ffi

Signed-off-by: ossdev <ossdev@puresoftware.com>

### CODE REVIEW

**Comment by ossdev07** [comment]
@headius please merge this pull request

**Comment by ossdev07** [comment]
@headius as changes of jnr-ffi is pending to be merged to support aarch64 can you please check this request

**Comment by rhenwood-arm** [comment]
@headius can this change have some attention? I am interested to see it progress.

**Comment by headius** [comment]
Sorry for the delays on this, everyone. Travel-heavy summer came to an end today! I'll review and merge today.

**Comment by headius** [comment]
@ossdev07 Do you consent to relicensing this as Apache-2? That would be simpler as it aligns with the rest of jnr-*.

**Comment by headius** [comment]
I have pushed the pom.xml bits necessary for releasing this and deployed a snapshot build to the Sonatype snapshot repo. We can push a full release any time after we settle the licensing issue.

One note: this uses binary literals, which means unlike the rest of jnr-* it requires Java 7 or higher. That's probably not a big deal though.

**Comment by headius** [comment]
@ossdev07 I would like to add you as a maintainer for this project, is that ok?

**Comment by ossdev07** [comment]
@headius Sure, it would be great to be a maintainer of this project.... I'll push licencing changes with apache-2

**Comment by headius** [comment]
@ossdev07 I'll also add you as a contributor on jnr-ffi so you can finish up any final tweaks to integrate a64asm.

**Comment by ossdev07** [comment]
@headius Sure.

**Comment by ossdev07** [comment]
@headius licensing issue for Apache 2.0 is settled now, We can push a full release 
Thanks

**Pull request merged**
